name: Count Lines of Code

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master

jobs:
  count-loc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cloc
        run: sudo apt-get install -y cloc

      - name: Count lines of code
        run: cloc .
        
      - name: Upload result
        run: cloc . > cloc_report.txt

      - name: Display cloc output
        run: cat cloc_report.txt

      - name: Upload cloc report artifact
        uses: actions/upload-artifact@v3
        with:
          name: cloc-report
          path: cloc_report.txt
